
spring:
  application:
    name: micro-service-demo1
  cloud:
#    config:
#      enabled: false
    openfeign:
      # 开启断路器功能
      circuitbreaker:
        enabled: true
    loadbalancer:
      cache:
        enabled: true
      configurations:
        default:
          type: CUSTOM
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8999/eureka/
server:
  port: 8788

resilience4j:
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true # 注册健康指标，用于监控断路器的状态
        sliding-window-size: 100 # 滑动窗口的大小，用于记录最近的请求数
        failure-rate-threshold: 50 # 当失败率超过 50% 时，断路器会打开，进入打开状态
        wait-duration-in-open-state: 10000 # 断路器在打开状态下的等待时间（毫秒）
        permitted-number-of-calls-in-half-open-state: 10
        minimum-number-of-calls: 10
    instances:
      exampleServiceCircuitBreaker:
        base-config: default
  retry:
    configs:
      default:
        maxAttempts: 3 # 最大重试次数
        waitDuration: 500 # 等待时间（毫秒）后进行重试
    instances:
      exampleServiceRetry:
        baseConfig: default
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logging:
  level:
    root: INFO
    com.baomidou.mybatisplus: DEBUG
    org.mybatis: DEBUG
    org.springframework: INFO
